Fix #1614: Add `--no-schema` option to `litestar routes` command.
litestar-org/litestar pull request #1637
Opened 2023-05-08 17:01 UTC by solzard

### Pull Request Checklist

[//]: # "Please review the [Litestar contribution guidelines](https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst) for this repository."

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

### Description

[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

### Close Issue(s)

[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

2023-05-09 11:46 UTC, peterschutt commented
Maybe this is too rigid - we document how to rename the path the openapi docs are served at here: https://docs.litestar.dev/2/usage/openapi.html#subclassing-openapicontroller - and so this wouldn't work if that was done.

How about something more general, like `--exclude=/schema/.*` where the value is interpreted as a regex and any route that matches is excluded from output?

@litestar-org/maintainers, thoughts?

2023-05-09 12:34 UTC, solzard commented
How about this modification honoring `app.openapi_config`?

```python
from litestar.app import DEFAULT_OPENAPI_CONFIG

openapi_config = app.openapi_config if app.openapi_config is not None else DEFAULT_OPENAPI_CONFIG
schema_path = openapi_config.openapi_controller.path  # /schema or user-defined path

for route in sorted(app.routes, key=lambda r: r.path):
    if no_schema and route.path.startswith(schema_path):
        continue

    ...
```

2023-05-11 01:55 UTC, JacobCoffee requested changes

2023-05-11 01:55 UTC, JacobCoffee commented on litestar/cli/commands/core.py
> +@option("--no-schema", help="Exclude shema routes", is_flag=True, default=False)
```suggestion
@option("--no-schema", help="Exclude schema routes", is_flag=True, default=False)
```

2023-05-11 02:04 UTC, peterschutt commented
> Or, how about this modification honoring `app.openapi_config`?
> 
> ```python
> ...
> 
> from litestar.app import DEFAULT_OPENAPI_CONFIG
> 
> openapi_config = app.openapi_config or DEFAULT_OPENAPI_CONFIG
> schema_path = openapi_config.openapi_controller.path  # /schema or user-defined path
> 
> for route in sorted(app.routes, key=lambda r: r.path):
>     if no_schema and route.path.startswith(schema_path):
>         continue
> 
>     ...
> ```

I still prefer the regex based exclude solution as I think it is generally more useful, however I haven't had much to do with developing this CLI, so others in here would have an opinion that would outweigh mine.

2023-05-12 10:20 UTC, provinzkraut commented
> however I haven't had much to do with developing this CLI, so others in here would have an opinion that would outweigh mine.

I like the regex idea, and I want to throw another one into the ring: 
Make `--no-schema` the default, and instead add a switch to include those routes. The regex thing could then be added independently.

2023-05-18 22:39 UTC, peterschutt commented
> I like the regex idea, and I want to throw another one into the ring:
> Make `--no-schema` the default, and instead add a switch to include those routes. The regex thing could then be added independently.

I think it would make sense to do both at the same time then. Implement the regex exclude option, and add a default regex exclude that excludes the configured schema route path, and have that behavior configurable with `--no-schema=False`.

Will you be continuing with this @solzard? Absolutely no pressure, just curious.

2023-05-19 02:52 UTC, solzard commented
Yes, I'm planning to do it this weekend.
Two questions:
1. If `--exclude` option is passed, should it override the default schema regex? Or, merge with it?
2. Should the CLI accepts several `--exclude` options? (e.g. `litestar routes --exclude=/foo/* --exclude=/bar/*`)

2023-05-19 02:55 UTC, peterschutt commented
> Yes, I'm planning to do it this weekend. Two questions:
> 
>     1. If `--exclude` option is passed, should it override the default schema regex? Or, merge with it?
> 
>     2. Should the CLI accepts several `--exclude` options? (e.g. `litestar routes --exclude=/foo/* --exclude=/bar/*`)

1. It should merge with it. Given the default behavior will be to exclude schema routes, it would be surprising if adding an `--exclude` resulted in display of the schema routes.
2. Yep.

Thanks heaps!

2023-08-13 12:42 UTC, Goldziher commented
@solzard ?

2023-09-23 08:24 UTC, provinzkraut commented
Closing this as stale

2023-09-23 08:24 UTC, closed without merging