feat(auth-middleware) don't auth OPTIONS and HEAD requests for SessionAuth middlerware
litestar-org/litestar pull request #2182
Opened 2023-08-19 23:11 UTC by Mattwmaster58

this breaks browser preflights on authenticated endpoints

### Pull Request Checklist

[x]: # "By submitting this issue, you agree to:"
[x]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[x]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
Follow up on #2160 which didn't address SessionAuth middleware. 

### Close Issue(s)
[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

- Fixes #2181

2023-08-19 23:34 UTC, Mattwmaster58 commented
there were some mypy issues, but most seemed unrelated to my code

2023-08-19 23:41 UTC, cofin approved these changes
LGTM.  I'll see if we can get these other errors cleaned up.

2023-08-20 07:19 UTC, provinzkraut requested changes

2023-08-20 07:19 UTC, provinzkraut commented on tests/unit/test_middleware/test_session/test_integration.py
> +) -> User | None:
```suggestion
) -> Optional[User]:
```

2023-08-20 07:19 UTC, provinzkraut commented on tests/unit/test_middleware/test_session/test_integration.py
> +from typing import Any, Literal
```suggestion
from typing import Any, Literal, Optional
```

2023-08-20 07:56 UTC, merged