fix: use os.replace instead of shutil.move for renaming file
litestar-org/litestar pull request #2223
Opened 2023-08-25 17:31 UTC by guacs

### Pull Request Checklist

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
[//]: # "Please describe your pull request for new release changelog purposes"
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the usage docs'"

- This PR uses `os.replace` instead of `shutil.move` for renaming files to ensure atomicity.

### Close Issue(s)
[//]: # "Please add in issue numbers this pull request will close, if applicable"
[//]: # "Examples: Fixes #4321 or Closes #1234"

2023-08-25 17:35 UTC, guacs commented
The current usage of `shutil.move` for renaming a file is not ensured to be atomic. It uses `os.rename` semantics under the hood, but the atomicity is not guaranteed across all platforms (Windows to be more specific) as per this [issue](https://github.com/python/cpython/issues/53074).

2023-08-25 18:06 UTC, Alc-Alc commented
> The current usage of `shutil.move` for renaming a file is not ensured to be atomic. It uses `os.rename` semantics under the hood, but the atomicity is not guaranteed across all platforms (Windows to be more specific) as per this [issue](https://github.com/python/cpython/issues/53074).
> 
> Also, a point to note is that, if the destination file exists `os.rename` will raise a `FileExistsError` in Windows, but `os.replace` will silently overwrite the existing file.

Can you point me where it says this is atomic on Windows? The docs don't seem to mention that

2023-08-25 18:52 UTC, Goldziher commented
@JacobCoffee - this is a good issue for a ruff rule. I see there is a new noqa added by this pr, so it should be brought to their attention I'd say

2023-08-25 18:56 UTC, provinzkraut commented
> @JacobCoffee - this is a good issue for a ruff rule. I see there is a new noqa added by this pr, so it should be brought to their attention I'd say

I don't think this would make a good rule really? Ruff can't know if you need the atomicity, and aside from that there are differences in behaviour of the functions that might otherwise be relevant.

2023-08-25 18:59 UTC, JacobCoffee commented
as an aside, I would be interested in enabling all ruff rules rather than the 75 line list we have now.

Reason being is that as new ruff rules are added, we wouldn't know.. if we enabled them all and selectively disabled then we would get the newest new there is, and possibly greatly shorten our pyproject.toml

2023-08-25 19:04 UTC, Goldziher commented
> as an aside, I would be interested in enabling all ruff rules rather than the 75 line list we have now.
> 
> Reason being is that as new ruff rules are added, we wouldn't know.. if we enabled them all and selectively disabled then we would get the newest new there is, and possibly greatly shorten our pyproject.toml

why not do it?

2023-08-25 19:05 UTC, Goldziher approved these changes

2023-08-25 19:06 UTC, provinzkraut requested changes
@guacs I second what @Alc-Alc said. I tried to confirm that `os.replace` is indeed (more) atomic than `shutil.move` but couldn't find anything. If this is indeed the case, this can be merged!

2023-08-25 19:33 UTC, Alc-Alc commented
> > The current usage of `shutil.move` for renaming a file is not ensured to be atomic. It uses `os.rename` semantics under the hood, but the atomicity is not guaranteed across all platforms (Windows to be more specific) as per this [issue](https://github.com/python/cpython/issues/53074).
> > Also, a point to note is that, if the destination file exists `os.rename` will raise a `FileExistsError` in Windows, but `os.replace` will silently overwrite the existing file.
> 
> Can you point me where it says this is atomic on Windows? The docs don't seem to mention that

If I understood what I read, internally `MoveFileEx` is used, which is also used by JDK [at least in this version](https://github.com/frohoff/jdk8u-jdk/blob/da0da73ab82ed714dc5be94acd2f0d00fbdfe2e9/src/windows/classes/sun/nio/fs/WindowsFileCopy.java#L291) for atomic move. Also as per one of the answer [here](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/449bb49d-8acc-48dc-a46f-0760ceddbfc3/movefileexmovefilereplaceexisting-ntfs-same-volume-atomic) (not the entire answer)

> It is very possible for MoveFile to be atomic, but it is also possible for something to go wrong and for it to fall back to a non-atomic behavior even if the underlying filesystem supports atomic rename.

Just posting this here for documentation purposes.

2023-08-26 04:12 UTC, guacs commented
I wasn't able to find direct documentation that states that `os.replace` is atomic in Windows, but I think `os.replace` is the best attempt at an atomic rename. It's what is used by Python in its `importlib` for an atomic write as seen [here](https://github.com/python/cpython/blob/8ba47146111d714c7b61825d43b52311d9be366d/Lib/importlib/_bootstrap_external.py#L195). The following is a comment in that `_write_atomic` function:

>   We first write data to a temporary file, and then use os.replace() to perform an atomic rename. 

Also, this [issue](https://github.com/python/cpython/issues/58169) is the one that changes from using `os.unlink` followed by `os.rename` to instead use `os.replace`.

2023-08-26 08:53 UTC, provinzkraut approved these changes

2023-08-26 08:54 UTC, provinzkraut commented
Thanks @guacs and @Alc-Alc for investigating this!

2023-08-26 08:54 UTC, merged