feat: jinja async support
litestar-org/litestar pull request #2359
Opened 2023-09-25 13:51 UTC by geeshta

### Pull Request Checklist

[//]: # "By submitting this issue, you agree to:"
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md)"
[//]: # "- follow Litestar's [Contribution Guidelines](https://litestar.dev/community/contribution-guide)"

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR

### Description
After #2195 , it is now possible to initiate Jinja env with `enable_async=True`. Litestar needs a way to recognize this and call `render_async` instead of the standard async. In this PR:
- `TemplateProtocol` was extended with a `render_async` method
- `TemplateEngineProtocol` was extended with `is_async` property
- For other existing engines (mako, minijinja) that do not support async, the former raises `NotImplementedError` and the latter always returns `False`

Somewhere in an async context, we need to `await` rendering of the template. The first possible place is `start_response` in `ASGIResponse`. However this class already counts on having the body and content length available. To solve this:

- New class `ASGITemplateResponse` was created with modified slots and constructor
- The template, context and `is_async` information is passed into it
- Most of the logic from `ASGIResponse` constructor was moved to an async function, where the template will be rendered sync or async and the `content_length` will be assigned along with more validation
- This is then awaited from within `start_response`

I tested it in the included test app and it seems to work. Just setting the engine to `enable_async` true lead to an exception (see #651 )

### Close Issue(s)
[//]: # Implements #651 

-

2023-09-25 14:02 UTC, provinzkraut reviewed
Looks good in general. I'm not so sure about the `ASGITemplateResponse` though. These were intended to be low-level responses, dealing with already rendered/encoded content. This is effectively breaks that separation. I'm not sure though what a better way to handle this would be.

One thing we could consider is enabling passing an awaitable / container type as `body`, which could then be awaited inside `start_response`. This would also allow us to handle this more efficiently / cleanly in the file responses and separate the concerns better.

@litestar-org/maintainers, specifically @peterschutt, what do you think?

2023-09-25 14:37 UTC, provinzkraut requested changes

2023-09-25 15:11 UTC, geeshta commented on litestar/response/template.py
> +        self.status_code = status_code
@provinzkraut The checks in the `super().__init__()` call make sense when you already have a body that's why I moved them to the async `prepare_content()` method.
This way they would run twice, once the instance is constructed with an empty body and then second time in `prepare_content`

2023-09-26 01:32 UTC, peterschutt commented
> I'm not so sure about the ASGITemplateResponse though. These were intended to be low-level responses, dealing with already rendered/encoded content. This is effectively breaks that separation.

I agree  - we don't have the right abstraction between the response/asgi response when we need async context to generate the content (e.g., files, and this). However, the precedent is already there and I don't think this PR is doing anything worse than what we are already doing.

> One thing we could consider is enabling passing an awaitable / container type as body, which could then be awaited inside start_response. This would also allow us to handle this more efficiently / cleanly in the file responses and separate the concerns better.

I think this is going down the right path - it think it would need to be some sort of callback that receives the response in an async context and can set body, headers and content length etc.

2023-09-26 07:54 UTC, euri10 commented
> @litestar-org/maintainers, specifically @peterschutt, what do you think?

quite some time ago when they added async support I tested it, found like everyone else that this was slower than the sync version, I dont think this changed, see some improvements in 2021 in 3.03, but I have to admit I've not followed this too closely.
This comment summarized at the time pretty well the state of jinja async :  https://github.com/aio-libs/aiohttp-jinja2/issues/152#issuecomment-426173834 
To be fair, I don't see what having this feat. brings to the table

2023-09-30 10:20 UTC, provinzkraut commented on litestar/response/template.py
> +        self.status_code = status_code
I'm not sure I follow. Why would this necessitate duplicating *all* of the logic in `ASGIResponse.__init__`?

2023-09-30 10:22 UTC, provinzkraut commented
> > @litestar-org/maintainers, specifically @peterschutt, what do you think?
> 
> quite some time ago when they added async support I tested it, found like everyone else that this was slower than the sync version, I dont think this changed, see some improvements in 2021 in 3.03, but I have to admit I've not followed this too closely. This comment summarized at the time pretty well the state of jinja async : [aio-libs/aiohttp-jinja2#152 (comment)](https://github.com/aio-libs/aiohttp-jinja2/issues/152#issuecomment-426173834) To be fair, I don't see what having this feat. brings to the table

I think this is a valid point. Maybe we should evaluate whether there is actually a demand for this feature before going ahead with this?

@litestar-org/members please chime in here.

2023-10-01 01:15 UTC, guacs commented
Personally, I'm not a fan of the approach for taken for this, but I'm not against this feature being added. 

> One thing we could consider is enabling passing an awaitable / container type as `body`, which could then be awaited inside `start_response`. This would also allow us to handle this more efficiently / cleanly in the file responses and separate the concerns better.

I think we should implement something along these lines, and then come back to this feature.

2023-10-01 17:40 UTC, closed without merging

2023-10-01 17:42 UTC, geeshta commented
I've created #2386 to address the topic of async generated responses more generally