downtype Pydantic types which cannot be instantiated
litestar-org/litestar pull request #2491
Opened 2023-10-22 19:23 UTC by jw-can

### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description

- downtype Pydantic types which cannot be instantiated (e.g. EmailStr)

### Close Issue(s)

- Fixes #2334

2023-10-23 05:58 UTC, peterschutt requested changes
Thanks for this!

A couple of comments.

I did some experimentation on types like `Json` earlier, and have made a PR into your fork with some suggestions based on that.

2023-10-23 05:58 UTC, peterschutt commented on tests/unit/test_contrib/test_pydantic/test_integration.py
> +def test_pydantic_correct_emailstr_succeeds() -> None:
In addition to the integration tests, we should unit test `PydanticDTOFactory.generate_field_definitions()` using a model with types that we expect to downcast as input.

2023-11-20 00:51 UTC, JacobCoffee commented
@jw-can anything to update here?

2023-11-20 08:02 UTC, jw-can commented
Hi @JacobCoffee 
I've been super busy the last weeks and unfortunately couldn't get to work on the forks I prepared for litestar.
This one's hanging on Pydantic tests but as far as I can remember functionally everything's there in this fork for the issue.

2024-03-06 22:44 UTC, bmle69 commented
Just chiming in here after looking to see if an issue already exists for this problem. Seeing the same for url fields using pydantic models for the URL field

``{
  "status_code": 400,
  "detail": "Unsupported type: <class 'str'> - at `$.website_url`"
}``

2024-03-31 02:17 UTC, peterschutt commented
Closed in favor of #3296 - thanks for taking a shot at this @jw-can. I've decided to take a more deliberate approach than relying on the openapi type.

2024-03-31 02:17 UTC, closed without merging