Handle HTTPExceptions from the TaskGroup
litestar-org/litestar pull request #2596
Opened 2023-11-01 21:11 UTC by smithk86

### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description
- Moved the `get_exception_group()` helper from `tests/helpers.py` to `litestar/utils/helpers.py` and updated the test references
- Updated `litestar/_kwargs/kwargs_model.py` to use `_ExceptionGroup = get_exception_group()` and catch HTTPExceptions coming from the `TaskGroup` and throw the first one.
- The good: Easy implementation; at least one HTTPException at a time will have visibility
- The bad: If multiple HTTPExceptions are thrown in a single TaskGroup, only the first one will be seen.

### Close Issue(s)
- Fixes #2594

2023-11-05 11:00 UTC, provinzkraut requested changes
Thanks @smithk86! I've left a few change requests.

2023-11-05 18:38 UTC, smithk86 commented
@provinzkraut I have reworked the changes with your suggestions. I also added an additional test to unit/test_dependency_batches.py to confirm `HTTPException` errors are handled correctly.

Cheers!

2023-11-07 20:32 UTC, provinzkraut commented
> @provinzkraut I have reworked the changes with your suggestions. I also added an additional test to unit/test_dependency_batches.py to confirm `HTTPException` errors are handled correctly.
> 
> Cheers!

Great! Can also also work in the type hunting stuff I opened a review comment about? As soon as that’s done this is good to go from my end.

2023-11-07 23:59 UTC, smithk86 commented on litestar/_kwargs/kwargs_model.py
> +_ExceptionGroup = get_exception_group()
@provinzkraut In the updated code, `_ExceptionGroup` is now referenced as an Exception in a try/except:

```python
try:
    async with create_task_group() as task_group:
        for dependency in batch:
            task_group.start_soon(resolve_dependency, dependency, connection, kwargs, cleanup_group)
except _ExceptionGroup as excgroup:
    raise excgroup.exceptions[0] from excgroup  # type: ignore[attr-defined]
```

2023-11-09 20:00 UTC, provinzkraut commented on litestar/_kwargs/kwargs_model.py
> +_ExceptionGroup = get_exception_group()
Ah, sorry, totally missed that!

2023-11-09 20:00 UTC, provinzkraut approved these changes

2023-11-09 20:01 UTC, provinzkraut commented
@JacobCoffee any idea what's going on with pdm there?

2023-11-10 14:07 UTC, smithk86 commented
> @JacobCoffee any idea what's going on in the CI with pdm?

I'm not sure if this helps at all but the checks were passing prior to Litestar v2.3.2 release. After the release, I rebased with main and did a force-push. The pdm stuff has been pretty sad ever since.

2023-11-10 17:47 UTC, provinzkraut commented
@smithk86 I merged the latest `main`; It has #2639, which should fix these errors.

2023-11-10 19:17 UTC, merged

2023-11-10 19:46 UTC, provinzkraut commented
@all-contributors add @smithk86 for code

2023-11-10 19:46 UTC, provinzkraut commented
@smithk86 Issues have been fixed and it's finally merged! Sorry it took so long! :)