docs: add nginx unit section
litestar-org/litestar pull request #2615
Opened 2023-11-04 08:43 UTC by Kumzy

### Pull Request Checklist

- [ ] New code has 100% test coverage
- [ ] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [ ] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
- [ ] Pre-Commit Checks were ran and passed
- [ ] Tests were ran and passed

### Description
This add a new deployment folder in the documentation in the **usage** section as described in #2609.
Add a sub-section about using NGINX Unit to run litestar

### Close Issue(s)

2023-11-04 16:32 UTC, JacobCoffee requested changes

2023-11-04 16:32 UTC, JacobCoffee commented on docs/usage/deployment/nginx-unit.rst
> +1. To install nginx-unit, refers to the `official documentation <https://unit.nginx.org/installation/>`_
```suggestion
To install ``nginx-unit``, refer to the `official documentation <https://unit.nginx.org/installation/>`_
```

2023-11-04 16:32 UTC, JacobCoffee commented on docs/usage/deployment/nginx-unit.rst
> +   .. tab-item:: macOS (Brew)
```suggestion
   .. tab-item:: macOS (`Brew <https://brew.sh/>`_)
```

2023-11-04 16:32 UTC, JacobCoffee commented on docs/usage/deployment/nginx-unit.rst
> +- On Linux-based systems, abstract UNIX sockets can be used as well: unix:@abstract_socket.
```suggestion
- A unique IP socket: ``127.0.0.1:80``, ``[::1]:8080``
- A wildcard that matches any host IPs on the port: ``*:80``
- On Linux-based systems, abstract UNIX sockets can be used as well: ``unix:@abstract_socket``.
```
sphinx will add a link to that `*`

2023-11-04 16:32 UTC, JacobCoffee commented on docs/usage/deployment/nginx-unit.rst
> +To update the nginx-unit service already running, use ``PUT`` method to send the ``unit.json`` file on the `/config` endpoint
```suggestion
To update the nginx-unit service already running, use ``PUT`` method to send the ``unit.json`` file on the ``/config`` endpoint
```

2023-11-04 16:32 UTC, JacobCoffee commented on docs/usage/deployment/index.rst
Can you move to docs/topics/deployment? Sorry 🙁

2023-11-04 16:32 UTC, JacobCoffee commented on docs/usage/deployment/nginx-unit.rst
Same as above on moving to Topics section

2023-11-04 16:33 UTC, JacobCoffee commented
Everything looks good to me except the move from Usage to Topics! 

Thanks

2023-11-04 19:12 UTC, Kumzy commented on docs/usage/deployment/index.rst
Done

2023-11-04 19:12 UTC, Kumzy commented on docs/usage/deployment/nginx-unit.rst
Done

2023-11-04 19:12 UTC, Kumzy commented on docs/usage/deployment/index.rst
Maybe the deployment section need a little introduction?

2023-11-04 19:13 UTC, Kumzy reviewed
Moved from usage to topic

2023-11-04 19:25 UTC, Kumzy reviewed
Forgot to review comments

2023-11-04 21:01 UTC, JacobCoffee approved these changes

2023-11-04 21:31 UTC, merged

2023-11-07 02:39 UTC, Alc-Alc commented
@all-contributors add @Kumzy to docs