feat(ci): add new feature notifier
litestar-org/litestar pull request #2889
Opened 2023-12-13 00:57 UTC by JacobCoffee

Adds new CI workflow triggeredon comment to request users update their target base

2023-12-13 00:57 UTC, JacobCoffee commented
[new feature]

2023-12-13 00:59 UTC, JacobCoffee commented
[new feature]

2023-12-13 01:01 UTC, JacobCoffee commented
[new feature]

2023-12-13 01:03 UTC, JacobCoffee commented
[new feature]

2023-12-13 01:03 UTC, JacobCoffee commented
asdf

2023-12-13 01:06 UTC, JacobCoffee commented
[new feature]

2023-12-13 01:06 UTC, JacobCoffee commented
[new feature]

2023-12-13 01:09 UTC, JacobCoffee commented
test

2023-12-13 01:15 UTC, JacobCoffee commented
[feature]

2023-12-16 10:50 UTC, provinzkraut requested changes

2023-12-16 10:50 UTC, provinzkraut commented on .github/workflows/pr-target.yml
After reading this again, I don't think the logic here makes sense.

The job will only run on `main`, so checking if it targets `main` and then failing if it's a feature PR is redundant. On the other hand, if we run this for all target branches, it will suggest that you target `develop` in any case, because that step doesn't take the target branch into account.

2024-01-07 10:48 UTC, merged