fix: add default value into get_logger_placeholder
litestar-org/litestar pull request #2919
Opened 2023-12-20 08:12 UTC by cbscsm

### Background
- Currently, `Litestar.get_logger` is `get_logger_placeholder` only when initialized by keyword argument `logging_config=None`.
  - We using this keyword argument as workaround for an issue like #2862
- `request.logger` is a property that returns `self.app.get_logger()`. It calls `Litestar.get_logger` with no argument. In standard library or picologging, it is allowed and will return root logger.
- code: https://github.com/litestar-org/litestar/blob/d8322b7a588a0a272d8b611d7d0c6ab1d2ccc326/litestar/connection/base.py#L268-L278
- But `get_logger_placeholder` doesn't allow calling it with no argument. So, when you initialize app with no logging_config and use `request.logger`, the error is not as intended.
- Actual
```text
TypeError: get_logger_placeholder() missing 1 required positional argument: '_'
```
- Expected
```text
ImproperlyConfiguredException: cannot call '.get_logger' without passing 'logging_config' to the Litestar constructor first
```

### Changes
- So I suggest to add default value `None` to sync normal signature of `get_logger` functions(in `logging` or `picologging`)

2023-12-21 03:59 UTC, guacs commented
@cbscsm thanks for this! I think this makes sense since it's the same for the standard library `getLogger` function as well. Could you add a test for this as well?

2023-12-21 14:34 UTC, cbscsm commented
I added a test case to check if right exception raised when get_logger_placeholder called without args.

2023-12-21 16:18 UTC, guacs requested changes

2023-12-21 16:18 UTC, guacs commented on tests/unit/test_logging/test_logging_config.py
> +        with pytest.raises(ImproperlyConfiguredException):
Could you add a `match` to make sure the exception message is the logging one? Just to confirm that the error is from the placeholder function.

2023-12-22 02:37 UTC, guacs approved these changes
Thank you!

2023-12-22 02:38 UTC, merged

2023-12-22 02:38 UTC, guacs commented
@all-contributors add @cbscsm for code, test