create a rate-limit configuration from a list of values
litestar-org/litestar pull request #3121
Opened 2024-02-19 20:29 UTC by ch-iv

## Description

- Adds ability to define a rate-limit configuration using a list of values

## Closes #1262

2024-03-03 10:37 UTC, provinzkraut requested changes
Hey @ch-iv, thanks for your contribution! Unfortunately, this can't go as it is now, since it would be a breaking change; It alters parts of the public API in a way that's not backwards compatible.

You can either try to make it work in a non-breaking way, or stash this PR for the next major version, where we could do a breaking change. 

A suggestion for how this could be made non-breaking:

Create a new middleware (e.g. `MultiRateLimitingMiddleware`) instead of modifying the existing one. Both could share a base class for the common functionalities, and then they could be used depending on the configuration provided.

2024-03-03 10:37 UTC, provinzkraut commented on litestar/middleware/rate_limit.py
> -        self.unit: DurationUnit = config.rate_limit[0]
We'll need to keep these attributes to remain backwards compatible. Otherwise this would be a breaking change.

2024-03-03 10:37 UTC, provinzkraut commented on litestar/middleware/rate_limit.py
> +    ) -> Send:
This is a breaking change as well

2024-03-03 10:37 UTC, provinzkraut commented on litestar/middleware/rate_limit.py
> +    ) -> dict[str, str]:
Also a breaking change

2024-03-17 18:09 UTC, JacobCoffee commented
Are we able to address concerns and rebase against the latest `develop` branch to finish this one up?
@ch-iv

2024-03-17 18:35 UTC, ch-iv commented
I am busy the coming week, but I can address it next week if that's ok. If time is an issue -- someone else can take over.

2024-03-26 01:51 UTC, peterschutt commented
What should we aim for here? Non-breaking in a minor, or v3?

2024-03-26 03:23 UTC, ch-iv commented
I think it is best kept for v3. Having two rate limit middleware classes is redundant and probably confusing to the user.

2024-04-05 20:38 UTC, closed without merging

2024-04-05 20:56 UTC, JacobCoffee commented
Sorry about this, but this should be reopened and pointed to `main`.