feat: Add `path` parameter to Litestar application class
litestar-org/litestar pull request #3314
Opened 2024-04-04 18:47 UTC by kedod

## Description

- Expose `path` parameter at `Litestar` application class level

At this moment if we want use prefixed path for all routes in the application we have to create 
dedicated router. E.g:
```python
from litestar import Litestar, Router, get

@get("/")
async def index() -> str:
    return "Hello, world!"

router = Router(path="/path", route_handlers=[index])

app = Litestar(route_handlers=[router])
```

This PR allows to set `path` on the `Litestar` application level.
Thanks to this we don't need additional `Router` class.

```python
from litestar import Litestar, get

@get("/")
async def index() -> str:
    return "Hello, world!"

app = Litestar(path="/path", route_handlers=[index])
```

2024-04-04 18:49 UTC, cofin approved these changes
LGTM

2024-04-05 05:12 UTC, JacobCoffee requested changes

2024-04-05 05:12 UTC, JacobCoffee commented on litestar/app.py
> +                with the application instance.
```suggestion
            path: A path fragment that is prefixed to all route handlers, controllers and routers associated
                with the application instance.
                
                .. versionadded:: 2.8.0
```

2024-04-05 05:12 UTC, JacobCoffee commented on litestar/testing/helpers.py
> +            with the application instance.
```suggestion
        path: A path fragment that is prefixed to all route handlers, controllers and routers associated
            with the application instance.
            
            .. versionadded:: 2.8.0
```

2024-04-05 05:12 UTC, JacobCoffee commented on litestar/testing/helpers.py
> +            with the application instance.
```suggestion
        path: A path fragment that is prefixed to all route handlers, controllers and routers associated
            with the application instance.
            
            .. versionadded:: 2.8.0
```

2024-04-05 05:12 UTC, JacobCoffee commented on litestar/config/app.py
> +    path: str = field(default="")
```suggestion
    path: str = field(default="")
    """A base path that prefixed to all route handlers, controllers and routers associated with the 
    application instance.
    
    .. versionadded:: 2.8.0
    """
```

2024-04-05 05:13 UTC, JacobCoffee commented
seems good :) thx

2024-04-05 18:33 UTC, merged