feat: Add support for v2 model_dump and v1 dict to pydantic plugin
litestar-org/litestar pull request #3327
Opened 2024-04-06 09:26 UTC by kedod

## Description

- Add support for additional V1 model_dump and V2 dict parameters in PydanticPlugin

This is a continuation of https://github.com/litestar-org/litestar/pull/3171
The last unresolved conversation is here https://github.com/litestar-org/litestar/pull/3171#discussion_r1544483848

## Closes #3147

2024-04-07 12:23 UTC, guacs requested changes

2024-04-07 14:08 UTC, Alc-Alc commented on litestar/types/serialization.py
> +PydanticV2FieldsListType: TypeAlias = "Set[int] | Set[str] | Dict[int, Any] | Dict[str, Any] | None"
just for my understanding, is it ok to have ` | None` in the type alias? I would prefer `PydanticV2FieldsListType | None` just to be explicit, but I am not sure if that is the norm 🙂

2024-06-16 07:43 UTC, provinzkraut commented
@kedod I started something similar over in #3573, not realising this PR exists :)
Would you mind merging the stuff I did there over here? No need to implement these things twice.

2024-07-03 20:45 UTC, Anu-cool-007 commented
Hi @provinzkraut, I've created this new PR that combines this one with strict validation: #3608

2024-07-06 12:14 UTC, provinzkraut commented
Superseded by #3608

2024-07-06 12:14 UTC, closed without merging