docs: Document custom types
litestar-org/litestar pull request #3603
Opened 2024-06-27 08:23 UTC by stewit

## Description
- Add documentation that explains the usage of `type_decoders` and `type_encoders` in order to allow litestar to en/decode custom types via msgspec
- See question #3584

2024-06-27 14:09 UTC, JacobCoffee commented on docs/usage/custom-types.rst
> +=============
```suggestion
Custom types
============
```

2024-06-27 14:09 UTC, JacobCoffee commented on docs/usage/custom-types.rst
> +Among others, litestar supports Python's builtin dataclasses, Pydantic and msgspec for these tasks, defaulting to msgspec with json as serialization protocol.
```suggestion
Among others, Litestar supports Python's built-in dataclasses, Pydantic, and msgspec for these tasks, defaulting to msgspec with JSON as the serialization protocol.
```

2024-06-27 14:53 UTC, provinzkraut requested changes

2024-06-27 14:53 UTC, provinzkraut commented on docs/usage/custom-types.rst
> +Among others, litestar supports Python's builtin dataclasses, Pydantic and msgspec for these tasks, defaulting to msgspec with json as serialization protocol.
I don't think "defaulting to msgspec" is the correct phrasing here. Litestar only uses msgspec for serialisation to JSON. It *can* integrate with Pydantic and others, but doesn't use those to encode anything to JSON directly; It all goes through msgspec eventually.

I'm not sure msgspec needs to be mentioned in this part of the documentation in general, as it's more of an implementation detail. We *should* mention that that's how it works, but perhaps we can find a better place for that

2024-08-25 00:41 UTC, cofin commented
@all-contributors, please add @stewit for docs

2024-08-25 00:43 UTC, cofin approved these changes

2024-08-25 00:43 UTC, merged