feat(Pydantic): added parameters to pydantic plugin to support strict validation and type include/exclude
litestar-org/litestar pull request #3608
Opened 2024-07-03 20:43 UTC by Anu-cool-007

Combines the following stale PRs:

- #3573
- #3327

Closes #3572 and #3147 

Context: https://github.com/litestar-org/litestar/pull/3327#issuecomment-2171148195

2024-07-06 12:13 UTC, provinzkraut requested changes
Thanks @Anu-cool-007!

2024-07-06 12:13 UTC, provinzkraut commented on litestar/contrib/pydantic/__init__.py
> +            validate_strict: Pydantic 2.x models will use ``strict=True`` when calling ``.model_validate``
These should be the same docstring as in `PydanticInitPlugin`

2024-07-06 12:13 UTC, provinzkraut commented
@kedod can you review this one as well?

2024-07-06 19:18 UTC, Anu-cool-007 commented
@provinzkraut, is there a specific format for docstrings that I should use?

2024-07-10 18:19 UTC, provinzkraut requested changes
@Anu-cool-007 I went over the docstrings and made some suggestions. Aside from that this is good to go

2024-07-10 18:19 UTC, provinzkraut commented on litestar/contrib/pydantic/__init__.py
> +        :param validate_strict: Whether to use ``strict=True`` when calling ``.model_validate`` on Pydantic 2.x models
```suggestion
        :param exclude: Fields to exclude during serialization
        :param exclude_defaults: Fields to exclude during serialization when they are set to their default value
        :param exclude_none: Fields to exclude during serialization when they are set to ``None``
        :param exclude_unset: Fields to exclude during serialization when they arenot set
        :param include: Fields to exclude during serialization
        :param prefer_alias: Use the ``by_alias=True`` flag when dumping models
        :param validate_strict: Use ``strict=True`` when calling ``.model_validate`` on Pydantic 2.x models
```

2024-07-10 18:19 UTC, provinzkraut commented on litestar/contrib/pydantic/pydantic_init_plugin.py
> +        :param validate_strict: Whether to use ``strict=True`` when calling ``.model_validate`` on Pydantic 2.x models
```suggestion
        :param exclude_defaults: Fields to exclude during serialization when they are set to their default value
        :param exclude_none: Fields to exclude during serialization when they are set to ``None``
        :param exclude_unset: Fields to exclude during serialization when they arenot set
        :param include: Fields to exclude during serialization
        :param prefer_alias: Use the ``by_alias=True`` flag when dumping models
        :param validate_strict: Use ``strict=True`` when calling ``.model_validate`` on Pydantic 2.x models
```

2024-07-11 07:57 UTC, provinzkraut approved these changes

2024-07-11 08:27 UTC, merged

2024-07-11 17:43 UTC, Anu-cool-007 commented
@all-contributors add @Anu-cool-007 for code