docs: add graphql documentation
litestar-org/litestar pull request #3770
Opened 2024-10-01 00:13 UTC by aarcex3

## Description
Added documentation about the usage of `graphql` with litestar.

## Closes
#3317

2024-10-01 01:20 UTC, Alc-Alc commented on docs/usage/graphql.rst
> +Litestar does not support ``graphql`` out of the box. This can be done throught third party packages.
```suggestion
Litestar does not support ``graphql`` out of the box. This can be done through third party packages. 
```

2024-10-01 01:26 UTC, Alc-Alc commented on docs/usage/graphql.rst
> +Litestar does not support ``graphql`` out of the box. This can be done through third party packages.
```suggestion
Litestar does not support ``graphql`` out of the box. This can be done through third party packages.
```

2024-10-01 01:39 UTC, Alc-Alc approved these changes
thank you

2024-10-01 13:33 UTC, aarcex3 commented
> Do we really want to add a top-level usage section just to say that the feature is not supported? As a user, I'd be a bit confused by this.

Maybe add a code example? 🤔

2024-10-01 14:06 UTC, JacobCoffee requested changes
Having this is fine I think, but having it as such a small, standalone entry would indeed seem weird. I think I agree we should find a home for it somewhere else

2024-10-01 16:46 UTC, aarcex3 commented
> Having this is fine I think, but having it as such a small, standalone entry would indeed seem weird. I think I agree we should find a home for it somewhere else

Where do you suggest putting it? Maybe in guides/topics?

2024-10-07 20:20 UTC, provinzkraut commented
> @aarcex3 topics would be a good place imo! @provinzkraut thoughts?

I think it has the same problem in there as in the usage guide. There's not really a place where it fits in, and it doesn't merit its own page. IMO unless we have concrete plans to add a more lengthy section about integration with various 3rd party libraries, we should close this.

2024-10-08 01:04 UTC, aarcex3 commented
What about adding it to the awesome-litestar repo as a new section 🤔?
It would be simply a link to strawberry.

2024-10-08 03:02 UTC, JacobCoffee commented
Sure I'd accept that. It can just link to https://strawberry.rocks/docs/integrations/litestar

2024-10-08 13:32 UTC, aarcex3 commented
Made the pr. Please have a look. 😊
https://github.com/litestar-org/awesome-litestar/pull/5

2024-10-08 17:48 UTC, closed without merging